<a href="https://colab.research.google.com/github/LaxmikantRakhade/Machine_Learning_Practicals/blob/main/Practical_5_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lxmikant Rakhade   (CS23128)**

**Aim : To implement the random forest algorithm and evaluate the mode performance using appropriate metrics**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path="/content/drive/MyDrive/ML_DATASETS/banking - banking.csv"
df=pd.read_csv(path)
df.head(5)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,44,blue-collar,married,basic.4y,unknown,yes,no,cellular,aug,thu,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,0
1,53,technician,married,unknown,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0
2,28,management,single,university.degree,no,yes,no,cellular,jun,thu,...,3,6,2,success,-1.7,94.055,-39.8,0.729,4991.6,1
3,39,services,married,high.school,no,no,no,cellular,apr,fri,...,2,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,0
4,55,retired,married,basic.4y,no,yes,no,cellular,aug,fri,...,1,3,1,success,-2.9,92.201,-31.4,0.869,5076.2,1

In [ ]:
df.describe

<bound method NDFrame.describe of        age          job  marital            education  default housing loan  \
0       44  blue-collar  married             basic.4y  unknown     yes   no
1       53   technician  married              unknown       no      no   no
2       28   management   single    university.degree       no     yes   no
3       39     services  married          high.school       no      no   no
4       55      retired  married             basic.4y       no     yes   no
...    ...          ...      ...                  ...      ...     ...  ...
41183   59      retired  married          high.school  unknown      no  yes
41184   31    housemaid  married             basic.4y  unknown      no   no
41185   42       admin.   single    university.degree  unknown     yes  yes
41186   48   technician  married  professional.course       no      no  yes
41187   25      student   single          high.school       no      no   no

         contact month day_of_week  ...  campaign  pdays  previous  \
0       cellular   aug         thu  ...         1    999         0
1       cellular   nov         fri  ...         1    999         0
2       cellular   jun         thu  ...         3      6         2
3       cellular   apr         fri  ...         2    999         0
4       cellular   aug         fri  ...         1      3         1
...          ...   ...         ...  ...       ...    ...       ...
41183  telephone   jun         thu  ...         1    999         0
41184  telephone   may         thu  ...         2    999         0
41185  telephone   may         wed  ...         3    999         0
41186  telephone   oct         tue  ...         2    999         0
41187  telephone   may         fri  ...         4    999         0

          poutcome emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  \
0      nonexistent          1.4          93.444          -36.1      4.963
1      nonexistent         -0.1          93.200          -42.0      4.021
2          success         -1.7          94.055          -39.8      0.729
3      nonexistent         -1.8          93.075          -47.1      1.405
4          success         -2.9          92.201          -31.4      0.869
...            ...          ...             ...            ...        ...
41183  nonexistent          1.4          94.465          -41.8      4.866
41184  nonexistent          1.1          93.994          -36.4      4.860
41185  nonexistent          1.1          93.994          -36.4      4.857
41186  nonexistent         -3.4          92.431          -26.9      0.742
41187  nonexistent          1.1          93.994          -36.4      4.859

       nr_employed  y
0           5228.1  0
1           5195.8  0
2           4991.6  1
3           5099.1  0
4           5076.2  1
...            ... ..
41183       5228.1  0
41184       5191.0  0
41185       5191.0  0
41186       5017.5  0
41187       5191.0  0

[41188 rows x 21 columns]>

In [ ]:
df.shape

(41188, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp_var_rate    41188 non-null  float64
 16  cons_price_idx  41188 non-null  float64
 17  cons_conf_idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr_employed     41188 non-null  float64
 20  y               41188 non-null  int64
dtypes: float64(5), int64(6), object(10)
memory usage: 6.6+ MB

In [ ]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y'],
      dtype='object')

In [ ]:
df.isnull()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41184,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41185,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41186,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41187,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().any()

age               False
job               False
marital           False
education         False
default           False
housing           False
loan              False
contact           False
month             False
day_of_week       False
duration          False
campaign          False
pdays             False
previous          False
poutcome          False
emp_var_rate      False
cons_price_idx    False
cons_conf_idx     False
euribor3m         False
nr_employed       False
y                 False
dtype: bool

In [ ]:
df.isnull().any().any()

np.False_

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [age, job, marital, education, default, housing, loan, contact, month, day_of_week, duration, campaign, pdays, previous, poutcome, emp_var_rate, cons_price_idx, cons_conf_idx, euribor3m, nr_employed, y]
Index: []

[0 rows x 21 columns]

In [ ]:
X=df.drop(columns=['y'])
y=df['y']

In [ ]:

print(X)

       age          job  marital            education  default housing loan  \
0       44  blue-collar  married             basic.4y  unknown     yes   no
1       53   technician  married              unknown       no      no   no
2       28   management   single    university.degree       no     yes   no
3       39     services  married          high.school       no      no   no
4       55      retired  married             basic.4y       no     yes   no
...    ...          ...      ...                  ...      ...     ...  ...
41183   59      retired  married          high.school  unknown      no  yes
41184   31    housemaid  married             basic.4y  unknown      no   no
41185   42       admin.   single    university.degree  unknown     yes  yes
41186   48   technician  married  professional.course       no      no  yes
41187   25      student   single          high.school       no      no   no

         contact month day_of_week  duration  campaign  pdays  previous  \
0       cellular   aug         thu       210         1    999         0
1       cellular   nov         fri       138         1    999         0
2       cellular   jun         thu       339         3      6         2
3       cellular   apr         fri       185         2    999         0
4       cellular   aug         fri       137         1      3         1
...          ...   ...         ...       ...       ...    ...       ...
41183  telephone   jun         thu       222         1    999         0
41184  telephone   may         thu       196         2    999         0
41185  telephone   may         wed        62         3    999         0
41186  telephone   oct         tue       200         2    999         0
41187  telephone   may         fri       112         4    999         0

          poutcome  emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  \
0      nonexistent           1.4          93.444          -36.1      4.963
1      nonexistent          -0.1          93.200          -42.0      4.021
2          success          -1.7          94.055          -39.8      0.729
3      nonexistent          -1.8          93.075          -47.1      1.405
4          success          -2.9          92.201          -31.4      0.869
...            ...           ...             ...            ...        ...
41183  nonexistent           1.4          94.465          -41.8      4.866
41184  nonexistent           1.1          93.994          -36.4      4.860
41185  nonexistent           1.1          93.994          -36.4      4.857
41186  nonexistent          -3.4          92.431          -26.9      0.742
41187  nonexistent           1.1          93.994          -36.4      4.859

       nr_employed
0           5228.1
1           5195.8
2           4991.6
3           5099.1
4           5076.2
...            ...
41183       5228.1
41184       5191.0
41185       5191.0
41186       5017.5
41187       5191.0

[41188 rows x 20 columns]

In [ ]:
X= pd.get_dummies(X,dtype = int)

In [ ]:
X.head()

,age,duration,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,...,month_oct,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success
0,44,210,1,999,0,1.4,93.444,-36.1,4.963,5228.1,...,0,0,0,0,1,0,0,0,1,0
1,53,138,1,999,0,-0.1,93.200,-42.0,4.021,5195.8,...,0,0,1,0,0,0,0,0,1,0
2,28,339,3,6,2,-1.7,94.055,-39.8,0.729,4991.6,...,0,0,0,0,1,0,0,0,0,1
3,39,185,2,999,0,-1.8,93.075,-47.1,1.405,5099.1,...,0,0,1,0,0,0,0,0,1,0
4,55,137,1,3,1,-2.9,92.201,-31.4,0.869,5076.2,...,0,0,1,0,0,0,0,0,0,1

In [ ]:
X=pd.get_dummies(X,dtype=int)

In [ ]:
X.head()

,age,duration,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,...,month_oct,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success
0,44,210,1,999,0,1.4,93.444,-36.1,4.963,5228.1,...,0,0,0,0,1,0,0,0,1,0
1,53,138,1,999,0,-0.1,93.200,-42.0,4.021,5195.8,...,0,0,1,0,0,0,0,0,1,0
2,28,339,3,6,2,-1.7,94.055,-39.8,0.729,4991.6,...,0,0,0,0,1,0,0,0,0,1
3,39,185,2,999,0,-1.8,93.075,-47.1,1.405,5099.1,...,0,0,1,0,0,0,0,0,1,0
4,55,137,1,3,1,-2.9,92.201,-31.4,0.869,5076.2,...,0,0,1,0,0,0,0,0,0,1

In [ ]:
X.shape

(41188, 63)

In [ ]:
X.columns

Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp_var_rate',
       'cons_price_idx', 'cons_conf_idx', 'euribor3m', 'nr_employed',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'education_basic.4y', 'education_basic.6y',
       'education_basic.9y', 'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'education_unknown', 'default_no', 'default_unknown', 'default_yes',
       'housing_no', 'housing_unknown', 'housing_yes', 'loan_no',
       'loan_unknown', 'loan_yes', 'contact_cellular', 'contact_telephone',
       'month_apr', 'month_aug', 'month_dec', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'day_of_week_fri', 'day_of_week_mon', 'day_of_week_thu',
       'day_of_week_tue', 'day_of_week_wed', 'poutcome_failure',
       'poutcome_nonexistent', 'poutcome_success'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, test_size=0.25 , random_state=42)
X_train.shape, X_test.shape

((28831, 63), (10297, 63))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100,n_jobs=-1,max_depth=5,oob_score=True, random_state=42)
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [ ]:
y_pred = rf_classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [ ]:
print('Confusion Matrix')
cm=confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))

Confusion Matrix
[[9042  950]
 [  69  236]]

In [ ]:
print ('Accuracy Score')
print(accuracy_score(y_pred,y_test))

Accuracy Score
0.901039137612897

In [ ]:
rf_classifier.oob_score_

0.9022926710832091

In [ ]:
print('Classification Report')
print(classification_report(y_pred,y_test))

Classification Report
              precision    recall  f1-score   support

           0       0.99      0.90      0.95      9992
           1       0.20      0.77      0.32       305

    accuracy                           0.90     10297
   macro avg       0.60      0.84      0.63     10297
weighted avg       0.97      0.90      0.93     10297

In [ ]:
rf=RandomForestClassifier(random_state=42,n_jobs=-1)

params={
    'max_depth':[2,3,5,10,20],
    'min_samples_leaf':[5,10,20,50,100,200],
    'n_estimators':[10,25,30,50,100,200]
}
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(estimator=rf, param_grid=params, cv=4 ,n_jobs=-1 ,verbose=1 ,scoring="accuracy")
grid_search.fit(X_train,y_train)

Fitting 4 folds for each of 180 candidates, totalling 720 fits

GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [ ]:
grid_search.best_score_

np.float64(0.9139467076496568)

In [ ]:
print(grid_search.best_params)

AttributeError: 'GridSearchCV' object has no attribute 'best_params'